### ISSUE TITLE
Request for iterative optimization code 

### ISSUE THREAD

**Issue by Amshaker** [MoMarky/ImpressionGPT#1]
Hi @MoMarky,

Thank you so much for your amazing work, it is really interesting.

Could you please share the code for the iterative prompting that measure the similarity and divide them into good and bad responses?

The current code is only with dynamic prompts and without iterative optimization. Please correct me if I am wrong.

I hope to hear from you soon.

Best regards,
Abdelrahman.

**Comment by Amshaker** [comment]
I run the provided notebook but the achieved rouge-1 is 45%. How can I reproduce the numbers of the paper (54%)?

**Comment by MoMarky** [comment]
> I run the provided notebook but the achieved rouge-1 is 45%. How can I reproduce the numbers of the paper (54%)?

Hi, thank for your interst of our work.

I've updated the code at ImpressionGPT.ipynb. 

Please use the code with the title "One Good And N Bad \n Mimic data" and "One Good And N Bad \n OpenI data".

Hope this can help you.
