### ISSUE TITLE
Request to Include a License in the Repository

### ISSUE THREAD

**Issue by qianchu** [MoMarky/ImpressionGPT#2]
Hello,

Thank you for sharing this repository and this is very impressive work! Your project is of great interest to me and I would love to use it for some of my own projects. However, I've noticed that there's no license currently attached to your repository. If possible, it would be very helpful if you could specify the terms under which other developers can use your code. In case you will find useful, the following link contains more information on which license to choose: https://choosealicense.com/.

Thanks for considering this request!

**Comment by MoMarky** [comment]
Hi,

Thank for your interst of our work.
I've updated this repo's LICENSE, Apache-2.0 license.

Hope I can help you, and look forward to your comments and suggestions.

**Comment by qianchu** [comment]
Awesome! Thank you so much!
